name: Running tests
on: [push, pull_request]
env:
  MODULE_NAME: handlebars_theme_handler
  DRUPAL_REPO: https://git.drupalcode.org/project/drupal.git
jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        drupal-version: [8.7.x, 8.8.x]
        php-version: [7.3, 7.4]
        exclude:
          - drupal-version: 8.7.x
            php-version: 7.4
          - drupal-version: 8.8.x
            php-version: 7.3
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: drupal
        ports:
          - 3306
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: Donwload Drupal
        run: |
          git clone --branch ${{ matrix.drupal-version }} ${{env.DRUPAL_REPO}} drupal --depth 1
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          cd drupal
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - uses: actions/checkout@v2
        with:
          path: drupal/modules/${{env.MODULE_NAME}}
      - name: Install composer dependencies
        run: |
          composer config --global discard-changes true
          composer global require drush/drush:~8.1
          echo "export PATH=$HOME/.composer/vendor/bin:$PATH" >> ~/.bash_profile
          source ~/.bash_profile
          cd drupal
          composer config repositories.custom_module path modules/${{env.MODULE_NAME}}
          composer require drupal/${{env.MODULE_NAME}}
          composer update
      - name: Install Drupal
        shell: bash -l {0}
        run: |
          cd drupal
          drush --yes site-install standard --db-url="mysql://root@127.0.0.1:${{job.services.mysql.ports[3306]}}/drupal"
          drush --yes en ${{env.MODULE_NAME}}
      - name: Run PhpUnit tests
        shell: bash -l {0}
        run: |
          cd drupal
          drush runserver 127.0.0.1:8080 &
          export SIMPLETEST_BASE_URL=http://localhost:8080
          export SIMPLETEST_DB=mysql://root@127.0.0.1:${{job.services.mysql.ports[3306]}}/drupal
          vendor/bin/phpunit -c core/phpunit.xml.dist modules/${{env.MODULE_NAME}}
